eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  # 注册到eureka点击时的Host
  instance:
    hostname: 127.0.0.1
spring:
  application:
    name: client
server:
  port: 8080